export const GAME_WIDTH = 960;
export const GAME_HEIGHT = 540;

export const BAKERY_STATIONS = {
  cafeTable: { label: "About Me", contentKey: "about" },
  recipeBook: { label: "Skills", contentKey: "skills" },
  displayCase: { label: "Projects", contentKey: "projects" },
  oven: { label: "Résumé", contentKey: "resume" },
  frostingCounter: { label: "Technologies", contentKey: "technologies" },
  decoratingCounter: { label: "Featured Project", contentKey: "featuredProject" },
  deliveryStation: { label: "GitHub", contentKey: "github" },
  bakeryDoor: { label: "Contact", contentKey: "contact" },
};

export const CUPCAKE_STEPS = [
  {
    id: "ingredients",
    number: 1,
    station: "Ingredients",
    stationId: "cafeTable",
    questLabel: "Gather the Ingredients",
    portfolioSection: "About Me",
    instruction: "Visit the ingredients station.",
    completionMessage: "The ingredients are ready for your recipe.",
    content: "Add your biography, interests, and portfolio story here.",
    link: null,
    interactionType: "arrival",
    ingredientItems: [
      { id: "egg", label: "Eggs", fact: "Add a short personal fact." },
      { id: "butter", label: "Butter", fact: "Add a detail about your background." },
      { id: "flour", label: "Flour", fact: "Add a value or strength." },
      { id: "sugar", label: "Sugar", fact: "Add a fun detail." },
    ],
  },
  {
    id: "batter",
    number: 2,
    station: "Batter",
    stationId: "recipeBook",
    questLabel: "Mix the Batter",
    portfolioSection: "Skills",
    instruction: "Head to the mixing station.",
    completionMessage: "The batter is smooth and ready for the tray.",
    content: "Add your languages, frameworks, tools, and strengths here.",
    link: null,
    interactionType: "arrival",
  },
  {
    id: "tray",
    number: 3,
    station: "Assembly",
    stationId: "displayCase",
    questLabel: "Fill the Cupcake Tray",
    portfolioSection: "Projects",
    instruction: "Visit the assembly station.",
    completionMessage: "The tray is filled with ideas worth exploring.",
    content: "Add your projects, technologies, and live demos here.",
    link: null,
    interactionType: "arrival",
  },
  {
    id: "baking",
    number: 4,
    station: "Baking",
    stationId: "oven",
    questLabel: "Bake the Cupcakes",
    portfolioSection: "Résumé",
    instruction: "Bring the tray to the oven.",
    completionMessage: "Your experience is baking nicely.",
    content: "Add your résumé details and link here.",
    link: null,
    interactionType: "arrival",
  },
  {
    id: "frosting",
    number: 5,
    station: "Frosting",
    stationId: "frostingCounter",
    questLabel: "Frost the Cupcakes",
    portfolioSection: "Technologies",
    instruction: "Visit the frosting station, then tap to frost.",
    completionMessage: "Perfectly frosted. Your technology stack is ready to serve.",
    content: "Add the technologies you use and the problems you enjoy solving.",
    link: null,
    interactionType: "button",
  },
  {
    id: "decorating",
    number: 6,
    station: "Decorating",
    stationId: "decoratingCounter",
    questLabel: "Add the Decorations",
    portfolioSection: "Featured Project",
    instruction: "Visit the decorating station.",
    completionMessage: "The featured project has its finishing touches.",
    content: "Add a featured project case study here.",
    link: null,
    interactionType: "arrival",
  },
  {
    id: "packaging",
    number: 7,
    station: "Packaging",
    stationId: "deliveryStation",
    questLabel: "Package the Order",
    portfolioSection: "GitHub",
    instruction: "Bring the cupcakes to the packaging station.",
    completionMessage: "The order is packed and ready to ship.",
    content: "Add your GitHub and deployed project links here.",
    link: null,
    interactionType: "arrival",
  },
  {
    id: "serving",
    number: 8,
    station: "Serving",
    stationId: "bakeryDoor",
    questLabel: "Serve the Customer",
    portfolioSection: "Contact",
    instruction: "Deliver the finished order.",
    completionMessage: "The cupcake is served. Thanks for stopping by.",
    content: "Add your email, LinkedIn, or preferred contact details here.",
    link: null,
    interactionType: "arrival",
  },
];

export const COLORS = {
  cream: "#f8edd8",
  parchment: "#f2d6ad",
  pink: "#e9a6a4",
  red: "#ad4d4b",
  brown: "#623f36",
  golden: "#f0c96b",
  cocoa: "#3d2929",
  sage: "#9eaf87",
};
